version: "3.8"
services:
  db:
    image: postgres:13.3-alpine
    restart: always
    container_name: construction--db
    environment:
      POSTGRES_USER: USER
      POSTGRES_PASSWORD: PASSWORD
      POSTGRES_DB: DATABASE
    networks:
      - api_db_network
  api:
    # image: gary23w/lfbuilders-rest-api:first
    build: .
    command: python3 run.py
    restart: always
    container_name: construction--api
    volumes:
      - .:/app
    ports:
      - 8080:8080
    networks:
      - api_db_network
    depends_on:
      - db
    environment:
      DATABASE_HOST: db
      DATABASE_USER: USER
      DATABASE_PASSWORD: PASSWORD
      DATABASE_NAME: DATABASE

networks:
  api_db_network:
    driver: bridge
